### PR TITLE
formatSourceAndFixImports instead of just format

### LINKED ISSUE #11: Plugin doesn't reorganize imports??
When I run the formatter via the plugin it doesn't seem to reorganize imports. 

I tried running the standalone https://github.com/google/google-java-format/releases/download/google-java-format-1.6/google-java-format-1.6-all-deps.jar and it does organize imports.

What gives? I can't find anything in the source code that would affect this...

### PR DESCRIPTION
**Pull request by jakub-bochenski**
Fixes #11 
Probably we want to add an option to control this to preserve backwards compatibility, this version is just to give an idea of how to fix it

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Added an option to control this that defaults to previous behaviour

**Comment by talios** [comment]
1.6.3 release and winging it's way to central.

**Comment by jakub-bochenski** [comment]
I confirm I was able to download 1.6.3 from central today

**Comment by jakub-bochenski** [comment]
Actually there is a little hiccup, see #13

**Pull request merged**
